---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1
  - 2.3
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 4.0"
  - PUPPET_VERSION="~> 3.0" FUTURE_PARSER=yes
matrix:
  exclude:
    - rvm: 2.3
      env: PUPPET_VERSION='~> 3.0'
